Traceback (most recent call last):
  File "/home/robson/miniconda3/envs/book/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/robson/miniconda3/envs/book/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/robson/miniconda3/envs/book/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/robson/miniconda3/envs/book/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/robson/miniconda3/envs/book/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/robson/miniconda3/envs/book/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/robson/miniconda3/envs/book/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/robson/miniconda3/envs/book/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Importando as bibliotecas
import pandas as pd
from anonymizedf.anonymizedf import anonymize

# Criando um DataFrame com as 3 primeiras amostras do exemplo anterior
dados = {'Nome': ['Ana', 'BÃ¡rbara', 'ClÃ¡udia'],
        'Altura': [175, 162, 161],
        'Idade': [25, 37, 45],
        'PressÃ£o': [132, 90, 140],
        'Temperatura': [38, 37, 39],
        'Sexo': ['Feminino', 'Feminino', 'Feminino'],
        'Escolaridade': ['Superior', 'Nenhuma', 'Superior'],
        'DiagnÃ³stico': ['Doente', 'SaudÃ¡vel', 'SaudÃ¡vel']}

df = pd.DataFrame(dados)
        
# Anonimizando os dados
an = anonymize(df)
an.fake_names('Nome')
an.fake_whole_numbers('Altura')
an.fake_whole_numbers('Idade')
an.fake_whole_numbers('PressÃ£o')
an.fake_whole_numbers('Temperatura')
an.fake_categories('Sexo')
an.fake_categories('Escolaridade')
an.fake_categories('DiagnÃ³stico')

# an.fake_dates('Coluna') 
# an.fake_decimal_numbers('Coluna')

# Dados anonimizados
df.iloc[:, 8:16]
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 2[0m
[1;32m      1[0m [38;5;66;03m# Importando as bibliotecas[39;00m
[0;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01manonymizedf[39;00m[38;5;21;01m.[39;00m[38;5;21;01manonymizedf[39;00m [38;5;28;01mimport[39;00m anonymize
[1;32m      5[0m [38;5;66;03m# Criando um DataFrame com as 3 primeiras amostras do exemplo anterior[39;00m

[0;31mModuleNotFoundError[0m: No module named 'pandas'
ModuleNotFoundError: No module named 'pandas'

